version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    target-branch: development
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "type: maintenance"
      - "area: ci-release"
      - "needs: decision"
  - package-ecosystem: github-actions
    directory: /
    target-branch: development
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "type: maintenance"
      - "area: ci-release"
      - "needs: decision"
